## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

fl_caster_rotation_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: fl_caster_rotation_joint
  required_drive_mode: 1
fr_caster_rotation_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: fr_caster_rotation_joint
  required_drive_mode: 1
b_caster_rotation_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: b_caster_rotation_joint
  required_drive_mode: 1

## twist_controller
twist_controller:
  type: cob_omni_drive_controller/WheelController
  required_drive_mode: 3
  #max_rot_velocity: 1.0
  #max_trans_velocity: 1.0
  timeout: 0.5

  defaults: # default settings for all wheels, can per overwritten per wheel
    steer_ctrl: # Parameters for tuning Impedance-Controller
      spring: 15.0 #10.0
      damp: 2.75 #2.5
      virt_mass: 0.1 #0.1
      d_phi_max: 12.0 #100.0
      dd_phi_max: 17.0 #100.0

  wheels: &wheels # start front left, counter-clockwise for base_drive_chain compatibility
    - steer: fl_caster_rotation_joint
      drive: fl_caster_r_wheel_joint
    - steer: b_caster_rotation_joint
      drive: b_caster_r_wheel_joint
      # steer_neutral_position: 180
    - steer: fr_caster_rotation_joint
      drive: fr_caster_r_wheel_joint
